### ISSUE TITLE
Issue detecting FLT3 ITD

### ISSUE THREAD

**Issue by incubus09** [archerdxinc/suite_analysis#2]
Customer had an issue detecting an ITD that is present at 80% in the sample and can be seen in IGV, but is not represented in the analysis pipeline. It was not seen in the Structural Variations section, but seen at 14% in the SNP/Indel section. Please help to resolve. I am linking this request to the odoo card issue #519 for further investigation. There are notes present from both Aaron and Josh H.

-crystal

**Comment by amberlin** [comment]
Tickets are not openned in this repository.  please open in https://github.com/archerdxinc/analysis
